[build]
target = "{% if arch == "risc" %}riscv32imac-unknown-none-elf{% else %}thumbv8m.main-none-eabihf{% endif %}"

[env]
DEFMT_LOG = "debug"

{% if arch == "arm" %}[target.thumbv8m.main-none-eabihf]{% elsif arch == "risc" %}[target.riscv32imac-unknown-none-elf]{% else %}[target.'cfg(any(all(target_arch = "arm", target_os = "none"), all(target_arch = "riscv32", target_os = "none")))']{% endif %}
runner = "probe-rs run --chip RP235x"
#"elf2uf2-rs -d"
#"picotool load -u -v -x -t elf"
{% if arch != "both" %}rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",{% endif %}{% if arch != "both" %}
    "link-arg=-T{% endif %}{% if arch == "arm" %}link{% elsif arch == "risc" %}riscv{% endif %}{% if arch != "both" %}.x",
{% endif %}{% if arch != "both" %}    "-C",
    "link-arg=-Tdefmt.x",
{% if arch == "arm" %}    "-C",
    "target-cpu=cortex-m33",
{% endif %}]{% endif %}
{% if arch == "both" %}[target.riscv32imac-unknown-none-elf]
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Triscv.x",
    "-C",
    "link-arg=-Tdefmt.x",
]

[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "target-cpu=cortex-m33",
]{% endif %}
