[hooks]
pre = ["pre.rhai"]

[template]
exclude = ["*.bin"]

[placeholders.library]
choices = ["embassy (async)", "rp-hal (sync)"]
default = "embassy (async)"
prompt = "Select hardware platform to support"

[conditional.'library == "rp-hal (sync)"'.placeholders.architecture]
choices = ["ARMv8", "RISC-V", "Both"]
default = "ARMv8"
prompt = "Select processor architecture to support"
type = "string"

[conditional.'library != "rp-hal (sync)"'.placeholders.wifi]
default = false
prompt = "Enable WiFi?"
type = "bool"
